config/routes.rb
Rails.application.routes.draw do
  match "currency/set" => "currency#set"
  namespace :admin do
    resources :currencies do
      collection do
        get :synchronize
      end
    end
    resource :currency_settings
  end
end

app/models/adjustment_decorator.rb
Adjustment.class_eval do

  def amount
    if associated_with_completed_order?
      read_attribute(:amount)
    else
      Currency.convert_to_current(read_attribute(:amount))
    end
  end
  
  def amount=(value)
    if associated_with_completed_order?
      write_attribute(:amount, value)
    else
      write_attribute(:amount, Currency.convert_from_current(value))
    end
  end
  
  protected
  
  def associated_with_completed_order?
    order && order.state == 'complete'
  end
  
end

app/models/currency.rb
require 'money'

class Currency < ActiveRecord::Base
  
  default_scope :order => 'currencies.char_code ASC'
  
  validates :name, :presence => true
  validates :num_code,  :presence => true, :uniqueness => true, :numericality => true
  validates :char_code, :presence => true, :uniqueness => true
  validates :nominal, :numericality => true
  validates :value,   :numericality => true
  
  def base?
    self.char_code == self.class.base.char_code
  end
  
  def format_info
    I18n.t('number.currency.format', :locale => "currency_#{char_code}")
  end
  
  class << self
    
    def get(char_code, base_code = Spree::Currency::Config[:base_currency])
      if currency = Currency.find_by_char_code(char_code.to_s.upcase)
        Money.add_rate(base_code, currency.char_code, currency.value.to_f)
        Money.add_rate(currency.char_code, base_code, currency.nominal/currency.value.to_f)
      end
      currency
    end
    
    # Session
    
    def init(char_code, base_code = Spree::Currency::Config[:base_currency])
      Thread.current[:base_currency]    = get(base_code)
      Thread.current[:current_currency] = get(char_code) || self.base
    end
    
    def base
      Thread.current[:base_currency]
    end
    
    def base?
      self.base == self.current
    end
    
    def current
      Thread.current[:current_currency]
    end
    
    # Conversion
    
    def convert(value, from, to)
      return value if from == to
      converted = Money.new(value.to_f * 10000, from).exchange_to(to).to_f / 100
      value.is_a?(BigDecimal) ? BigDecimal.new(converted.to_s) : converted 
    end
    
    def convert_by_rate(value, rate)
      converted = value.to_f * rate.to_f
      value.is_a?(BigDecimal) ? BigDecimal.new(converted.to_s) : converted 
    end
    
    def convert_to_current(value)
      convert(value, self.base.char_code, self.current.char_code)
    end
    
    def convert_from_current(value)
      convert(value, self.current.char_code, self.base.char_code)
    end
    
  end
  
end

app/models/currency_configuration.rb
class CurrencyConfiguration < Configuration
  preference :base_currency, :string, :default => 'USD'
end

app/models/line_item_decorator.rb
LineItem.class_eval do
  
  def update_price!(currency = nil)
    self.base_price = self.variant.base_price
    self.price = Currency.convert(self.base_price, Currency.base.char_code, (currency || self.order.currency).char_code)
  end
  
end

app/models/order_decorator.rb
Order.class_eval do
  
  belongs_to :currency
  
  before_validation :handle_currency_change
  
  alias_method(:update_without_currency_exchange!, :update!) unless method_defined?(:update_without_currency_exchange!)
  def update!
    handle_currency_change(true)
    update_without_currency_exchange!
  end
  
  def rate_hash
    @rate_hash ||= available_shipping_methods(:front_end).collect do |ship_method|
      next unless cost = ship_method.calculator.compute(self)
      { :id => ship_method.id,
        :shipping_method => ship_method,
        :name => ship_method.name,
        :cost => Currency.convert_to_current(cost)
      }
    end.compact.sort_by{|r| r[:cost]}
  end
  
  protected
  
  def handle_currency_change(forced = false)
    self.currency ||= Currency.base
    
    if self.currency_id_changed? || forced
      return self.currency_id = self.currency_id_was if completed? # cop out
      
      self.currency_value   = self.currency.value
      self.currency_nominal = self.currency.nominal

      # pass along the current currency - accessing it from the reverse association
      # doesn't work, because the order was not saved yet...
      self.line_items.each { |item| item.update_price!(self.currency) }
    end
  end
  
end

app/models/variant_decorator.rb
Variant.class_eval do
  
  extend CurrencyExchange
  currency_exchange :price
  
  def base_price
    read_attribute(:price)
  end
  
end

app/controllers/admin/currencies_controller.rb
require 'exchange_services'

class Admin::CurrenciesController < Admin::ResourceController
  
  def synchronize
    if ExchangeService::update_rates(Spree::Currency::Config[:base_currency])
      flash[:notice] = t('manage_currencies.currencies_synchronized')
    else
      flash[:error] = t("manage_currencies.currencies_not_synchronized")
    end
    redirect_to admin_currencies_path
  end
  
end

app/controllers/admin/currency_settings_controller.rb
class Admin::CurrencySettingsController < Admin::BaseController
  def update
    Spree::Currency::Config.set(params[:preferences])
    currency = Currency.get(Spree::Currency::Config[:base_currency])
    currency.update_attributes(:value => 1.0, :nominal => 1.0) if currency
    respond_to do |format|
      format.html {
        redirect_to admin_currency_settings_path
      }
    end
  end
end

app/controllers/currency_controller.rb
class CurrencyController < Spree::BaseController
    
  def set
    if request.referer && request.referer.starts_with?("http://" + request.host)
      session["user_return_to"] = request.referer
    end
    
    bool = params[:currency] && currency = Currency.get(params[:currency])
    
    if bool && current_order.is_a?(Order)
      unless current_order.completed?
        Currency.init(currency.char_code)
        current_order.currency = currency
        bool = current_order.save # triggers callbacks
        current_order.update! if bool
      end
      session[:current_currency] = current_order.currency.char_code
    elsif bool
      session[:current_currency] = currency.char_code
    end
      
    if bool
      flash[:notice] = t(:currency_changed, :currency => currency.name)
    else
      flash[:error] = t(:currency_not_changed)
    end
    
    redirect_back_or_default(root_path)
  end
  
end

app/helpers/number_helper_decorator.rb
module ActionView
  module Helpers
    module NumberHelper
      alias_method(:rails_number_to_currency, :number_to_currency) unless method_defined?(:rails_number_to_currency)
      def number_to_currency(number, options = {})
        options[:currency] ||= Currency.current.char_code.upcase
        defaults = { :locale => "currency_#{options[:currency]}" }
        rails_number_to_currency(number, defaults.merge(options))
      end
    end
  end
end

app/views/admin/currencies/_form.html.erb
<table>
  <tr>
    <td><%= t("currency_name") %>: </td>
    <td>
      <%= error_message_on :currency, :name %>
      <%= f.text_field :name  %>
    </td>
  </tr>
  <tr>
    <td><%= t("currency_num_code") %>: </td>
    <td>
      <%= error_message_on :currency, :num_code %>
      <%= f.text_field :num_code  %>
    </td>
  </tr>
  <tr>
    <td><%= t("currency_char_code") %>: </td>
    <td>
      <%= error_message_on :currency, :char_code %>
      <%= f.text_field :char_code  %>
    </td>
  </tr>
  <tr>
    <td><%= t("currency_nominal") %>: </td>
    <td>
      <%= error_message_on :currency, :nominal %>
      <%= f.text_field :nominal  %>
    </td>
  </tr>
  <tr>
    <td><%= t("currency_value") %>: </td>
    <td>
      <%= error_message_on :currency, :value %>
      <%= f.text_field :value  %>
    </td>
  </tr>
</table>

app/views/admin/currencies/edit.html.erb
<h1><%= t("edit_currency") %></h1>
<%= form_for(:currency, :url => object_url, :html => { :method => :put }) do |f| %>
<%= render :partial => "form", :locals => { :f => f } %>
<p class="form-buttons">
  <%= button t("update") %>
  <%= link_to t('cancel'), collection_url %>
</p>
<% end -%>

app/views/admin/currencies/index.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
      <p><%= button_link_to t("manage_currencies.synchronize"), synchronize_admin_currencies_url, :icon => 'exclamation' %></p>
    </li>
    <li>
      <p><%= button_link_to t("add_currency"), new_object_url, :icon => 'add' %></p>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t("manage_currencies.title") %></h1>

<table class="index">
  <thead>
	<tr>
    <th><%= t("currency_name")%></th>
    <th><%= t("currency_code")%></th>
    <th><%= t("currency_value")%></th>
    <th><%= t("currency_date_req")%></th>
    <th><%= t("action") %></th>
	</tr>
  </thead>
  <tbody>
    <% @currencies.each do |currency|%>
    <tr id="<%= dom_id currency %>">
      <td width="350px"><% if currency.base? %><strong><%= currency.name %></strong> - <%= t('base_currency').downcase %><% else %><%= currency.name %><% end %></td>
      <td>
        <%= currency.char_code %> - <%= currency.num_code %>
      </td>
      <td><%= currency.value %></td>
      <td><%= l(currency.date_req) %></td>
      <td>
      	<%= link_to_edit currency %> &nbsp;
	      <% unless currency.base? %><%= link_to_delete currency %> &nbsp;<% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/currencies/new.html.erb
<h1><%= t("new_currency") %></h1>
<%= form_for(:currency, :url => collection_url) do |f| %>
<%= render :partial => "form", :locals => { :f => f } %>
<p class="form-buttons">
  <%= button t("create") %>
  <%= link_to t('cancel'), collection_url %>
</p>
<% end -%>

app/views/admin/currency_settings/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("currency_exchange_settings.title") %></h1>
<% options = Currency.all.map { |c| ["#{c.char_code} - #{c.name}", c.char_code] } %>
<%= form_tag(admin_currency_settings_path, :method => :put) do -%>
  <p>
    <label><%= t("base_currency") %>:</label>
    <%= select_tag 'preferences[base_currency]', options_for_select(options, Spree::Currency::Config[:base_currency]) %>
  </p>
  <p style="color: red; font-weight: bold">
    <%= t("currency_exchange_settings.warning") %>
  </p>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_currency_settings_url %>
  </p>
<% end -%>

app/views/admin/currency_settings/show.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("currency_exchange_settings.title") %></h1>

<table>
  <tr>
    <th scope="row"><%= t("base_currency") %>:</th>
    <td><%= Spree::Currency::Config[:base_currency] %></td>
  </tr>
</table>

<p>
  <%= link_to_with_icon('edit', t("edit"), edit_admin_currency_settings_path) %>
</p>